// <auto-generated />
using AgentCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentCoreDbContext))]
    [Migration("20260926083213_P7WorkPinnedPersona")]
    partial class P7WorkPinnedPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AdminEventRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc");

                    b.ToTable("AdminEvents", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftEvaluationResultRecord", b =>
                {
                    b.Property<string>("ResultId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("DraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecordedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultId");

                    b.HasIndex("DraftId", "ScenarioId", "RecordedAtUtc");

                    b.ToTable("AgentDefinitionDraftEvaluationResults", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftEvaluationScenarioRecord", b =>
                {
                    b.Property<string>("DraftId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequirementLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftId", "ScenarioId");

                    b.HasIndex("DraftId");

                    b.ToTable("AgentDefinitionDraftEvaluationScenarios", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftRecord", b =>
                {
                    b.Property<string>("DraftId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftId");

                    b.HasIndex("DefinitionId");

                    b.ToTable("AgentDefinitionDrafts", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftResourceRecord", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("DraftId");

                    b.HasIndex("DraftId", "LogicalPath")
                        .IsUnique();

                    b.ToTable("AgentDefinitionDraftResources", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionPublicationRecord", b =>
                {
                    b.Property<string>("DefinitionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MetadataRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PublishedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceDraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("DefinitionId", "Version");

                    b.ToTable("AgentDefinitionPublications", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionPublicationResourceRecord", b =>
                {
                    b.Property<string>("DefinitionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("DefinitionId", "Version", "ResourceId");

                    b.HasIndex("DefinitionId", "Version", "LogicalPath")
                        .IsUnique();

                    b.ToTable("AgentDefinitionPublicationResources", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Compatibility")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PersonaRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId");

                    b.HasIndex("DefinitionId")
                        .IsUnique()
                        .HasFilter("Compatibility = 1");

                    b.ToTable("AgentInstances", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ArtifactRecordRow", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceLogicalPath")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("SessionId");

                    b.ToTable("Artifacts", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AttachmentRecordRow", b =>
                {
                    b.Property<string>("AttachmentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BoundAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Readable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StageForNextTurn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttachmentId");

                    b.HasIndex("SessionId");

                    b.HasIndex("State", "ExpiresAtUtc");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.EntryRecord", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentRefsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvelopeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeardTextEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterruptReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelCatalogKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProviderAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceivedTextEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAdmissionFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("SessionId", "EntrySequence")
                        .IsUnique();

                    b.HasIndex("SessionId", "SourceEventId")
                        .IsUnique()
                        .HasFilter("SourceEventId IS NOT NULL");

                    b.ToTable("ConversationEntries", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.MessageAttachmentRow", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "AttachmentId");

                    b.HasIndex("SessionId");

                    b.ToTable("MessageAttachments", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.OwnerCapabilityRecord", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenHash");

                    b.ToTable("OwnerCapabilities", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ProfileRecord", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurablyDeletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PauseReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedPersonaJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PinnedPersonaRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RuntimeEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WorkspaceOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("SessionId");

                    b.HasIndex("AgentInstanceId");

                    b.HasIndex("DurablyDeletedAtUtc", "ArchivedAtUtc", "UpdatedAtUtc", "SessionId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SnapshotRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentCompletion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeadlineAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUserActivityAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LifecycleChangedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelCatalogKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProviderAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelSelectionSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingTopic")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeechLocaleOverride")
                        .HasColumnType("TEXT");

                    b.Property<long>("SummarizedThroughEntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SummaryFormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SummaryGeneratedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryModelCatalogKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModelProviderAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModelReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UserCancellationAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UserCompletionAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("SessionSnapshots", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.StructuredMemoryRecord", b =>
                {
                    b.Property<string>("MemoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginMemoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProvenanceRecordedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEntryIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersedesMemoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemoryId");

                    b.HasIndex("SessionId", "Status");

                    b.HasIndex("OwnerProfileId", "Kind", "SubjectKey")
                        .IsUnique()
                        .HasDatabaseName("IX_StructuredMemories_UserOwner_Kind_SubjectKey")
                        .HasFilter("Status = 0 AND Scope = 2");

                    b.HasIndex("SessionId", "Kind", "SubjectKey")
                        .IsUnique()
                        .HasFilter("Status = 0 AND Scope = 0");

                    b.HasIndex("OwnerInstanceId", "OwnerProfileId", "Kind", "SubjectKey")
                        .IsUnique()
                        .HasFilter("Status = 0 AND Scope = 1");

                    b.ToTable("StructuredMemories", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.TriggerOccurrenceRecord", b =>
                {
                    b.Property<string>("OccurrenceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("AdmittedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimLeaseExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DispositionReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DurableWorkItemId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("RoutingRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RoutingUpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduleRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("OccurrenceId");

                    b.HasIndex("Disposition", "ClaimLeaseExpiresAtUtc");

                    b.HasIndex("AgentInstanceId", "ProfileId", "DedupeKey")
                        .IsUnique();

                    b.HasIndex("AgentInstanceId", "ProfileId", "Disposition");

                    b.ToTable("TriggerOccurrences", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.TriggerRegistrationRecord", b =>
                {
                    b.Property<string>("RegistrationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorizationOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextOccurrenceAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleKind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScheduleRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationId");

                    b.HasIndex("AgentInstanceId", "ProfileId", "Status");

                    b.HasIndex("Status", "NextOccurrenceAtUtc", "RegistrationId");

                    b.ToTable("TriggerRegistrations", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.WorkApprovalRecord", b =>
                {
                    b.Property<string>("ApprovalId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CheckpointRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Consumed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DecidedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionGeneration")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreparedActionJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("ApprovalId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("WorkApprovals", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.WorkItemRecord", b =>
                {
                    b.Property<string>("WorkItemId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CancellationRequestedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckpointJson")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CheckpointOutputBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckpointRemainingOverallBudgetMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckpointStepCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimGeneration")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimLeaseExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClaimedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentApprovalId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FailureAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownEffectSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelCatalogKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProviderAlias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelReasoningEffort")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextRetryAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ObservedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedPersonaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProgressUpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResultCompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultText")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SideEffectActionHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SideEffectDisposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SideEffectToolCallId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SideEffectUpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkItemId");

                    b.HasIndex("SourceOccurrenceId")
                        .IsUnique();

                    b.HasIndex("Status", "ClaimLeaseExpiresAtUtc");

                    b.HasIndex("Status", "NextRetryAtUtc");

                    b.HasIndex("AgentInstanceId", "ProfileId", "CreatedAtUtc");

                    b.ToTable("WorkItems", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.EntryRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SnapshotRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", "Session")
                        .WithOne("Snapshot")
                        .HasForeignKey("AgentCore.Infrastructure.Persistence.SnapshotRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.WorkApprovalRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.WorkItemRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
