// <auto-generated />
using AgentCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentCoreDbContext))]
    [Migration("20260918013000_EntryFinishReason")]
    partial class EntryFinishReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ArtifactRecordRow", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceLogicalPath")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("SessionId");

                    b.ToTable("Artifacts", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AttachmentRecordRow", b =>
                {
                    b.Property<string>("AttachmentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BoundAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Readable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StageForNextTurn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttachmentId");

                    b.HasIndex("SessionId");

                    b.HasIndex("State", "ExpiresAtUtc");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.EntryRecord", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentRefsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvelopeJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeardTextEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivedTextEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAdmissionFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("SessionId", "EntrySequence")
                        .IsUnique();

                    b.HasIndex("SessionId", "SourceEventId")
                        .IsUnique()
                        .HasFilter("SourceEventId IS NOT NULL");

                    b.ToTable("ConversationEntries", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.MessageAttachmentRow", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "AttachmentId");

                    b.HasIndex("SessionId");

                    b.ToTable("MessageAttachments", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.OwnerCapabilityRecord", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenHash");

                    b.ToTable("OwnerCapabilities", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ProfileRecord", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurablyDeletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PauseReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingMode")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RuntimeEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WorkspaceOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("SessionId");

                    b.HasIndex("DurablyDeletedAtUtc", "ArchivedAtUtc", "UpdatedAtUtc", "SessionId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SnapshotRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUserActivityAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingTopic")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SummarizedThroughEntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("SessionSnapshots", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.EntryRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SnapshotRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", "Session")
                        .WithOne("Snapshot")
                        .HasForeignKey("AgentCore.Infrastructure.Persistence.SnapshotRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
