// <auto-generated />
using AgentCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentCoreDbContext))]
    partial class AgentCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ActivationRecord", b =>
                {
                    b.Property<string>("ActivationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmissionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AdmittedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivationId");

                    b.HasIndex("SessionId", "DedupeKey")
                        .IsUnique();

                    b.HasIndex("AgentInstanceId", "ProfileId", "BackgroundSourceKey")
                        .IsUnique()
                        .HasFilter("BackgroundSourceKey IS NOT NULL");

                    b.ToTable("Activations", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ActivationSourceEntryRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "EntryId");

                    b.HasIndex("EntryId");

                    b.HasIndex("ActivationId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ActivationSourceEntries", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AdminEventRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc");

                    b.ToTable("AdminEvents", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentCredentialBindingRecord", b =>
                {
                    b.Property<string>("BindingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("BindingId");

                    b.HasIndex("CredentialId");

                    b.HasIndex("AgentInstanceId", "CredentialId")
                        .IsUnique();

                    b.HasIndex("AgentInstanceId", "Reference")
                        .IsUnique();

                    b.ToTable("AgentCredentialBindings", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftEvaluationResultRecord", b =>
                {
                    b.Property<string>("ResultId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("DraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecordedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultId");

                    b.HasIndex("DraftId", "ScenarioId", "RecordedAtUtc");

                    b.ToTable("AgentDefinitionDraftEvaluationResults", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftEvaluationScenarioRecord", b =>
                {
                    b.Property<string>("DraftId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequirementLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftId", "ScenarioId");

                    b.HasIndex("DraftId");

                    b.ToTable("AgentDefinitionDraftEvaluationScenarios", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftRecord", b =>
                {
                    b.Property<string>("DraftId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftId");

                    b.HasIndex("DefinitionId");

                    b.ToTable("AgentDefinitionDrafts", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionDraftResourceRecord", b =>
                {
                    b.Property<string>("DraftId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftId", "ResourceId");

                    b.HasIndex("DraftId");

                    b.HasIndex("DraftId", "LogicalPath")
                        .IsUnique();

                    b.ToTable("AgentDefinitionDraftResources", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionPublicationRecord", b =>
                {
                    b.Property<string>("DefinitionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MetadataRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PublishedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceDraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("DefinitionId", "Version");

                    b.ToTable("AgentDefinitionPublications", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionPublicationResourceRecord", b =>
                {
                    b.Property<string>("DefinitionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("DefinitionId", "Version", "ResourceId");

                    b.HasIndex("DefinitionId", "Version", "LogicalPath")
                        .IsUnique();

                    b.ToTable("AgentDefinitionPublicationResources", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionResourceStateRecord", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EnabledOverride")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId", "ResourceId");

                    b.ToTable("AgentDefinitionResourceStates", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionSkillStateRecord", b =>
                {
                    b.Property<string>("AgentInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionSkillId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EnabledOverride")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentInstanceId", "DefinitionSkillId");

                    b.HasIndex("AgentInstanceId");

                    b.ToTable("AgentDefinitionSkillStates", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionBudgetsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HarnessManagementJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PersonaRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsOverridesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnattendedModelCatalogKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnattendedReasoningEffort")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId");

                    b.HasIndex("DefinitionId");

                    b.ToTable("AgentInstances", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentInstanceResourceRecord", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId", "ResourceId");

                    b.HasIndex("InstanceId", "LogicalPath")
                        .IsUnique();

                    b.ToTable("AgentInstanceResources", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentInstanceSkillRecord", b =>
                {
                    b.Property<string>("AgentInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Procedure")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Projection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredCapabilitiesJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDefinitionSkillId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceDefinitionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentInstanceId", "SkillId");

                    b.HasIndex("AgentInstanceId", "UpdatedAtUtc");

                    b.ToTable("AgentInstanceSkills", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentRunRecord", b =>
                {
                    b.Property<string>("AgentRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ApprovalExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextRetryAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentRunId");

                    b.HasIndex("ActivationId")
                        .IsUnique();

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_AgentRuns_SessionExecution")
                        .HasFilter("Status IN (1, 2, 7)");

                    b.HasIndex("Status", "NextRetryAtUtc", "CreatedAtUtc");

                    b.HasIndex("AgentInstanceId", "ProfileId", "SessionId", "CreatedAtUtc");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentWorkspaceRow", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("AgentInstanceId", "PathKey")
                        .IsUnique();

                    b.ToTable("AgentWorkspaceItems", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ArtifactRecordRow", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentRunId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceLogicalPath")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "AgentRunId");

                    b.ToTable("Artifacts", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AttachmentRecordRow", b =>
                {
                    b.Property<string>("AttachmentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BoundAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Readable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StageForNextTurn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttachmentId");

                    b.HasIndex("SessionId");

                    b.HasIndex("State", "ExpiresAtUtc");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AutomationRecord", b =>
                {
                    b.Property<string>("AutomationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorizationOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionTargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOverrideCatalogKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOverrideReasoningEffort")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextOccurrenceAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PresetVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportToSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresTools")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresVision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("AutomationId");

                    b.HasIndex("AgentInstanceId", "ProfileId", "Status");

                    b.HasIndex("Status", "NextOccurrenceAtUtc", "AutomationId");

                    b.ToTable("Automations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Automations_Destination", "(ExecutionTargetKind = 0 AND TargetSessionId IS NULL) OR (ExecutionTargetKind = 1 AND TargetSessionId IS NOT NULL AND ReportToSessionId IS NULL)");

                            t.HasCheckConstraint("CK_Automations_Mode", "TriggerMode IN (0,1)");

                            t.HasCheckConstraint("CK_Automations_Preset", "(PresetId IS NULL AND PresetVersion IS NULL) OR (PresetId IS NOT NULL AND PresetVersion >= 1)");
                        });
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AutomationTriggerRecordEntity", b =>
                {
                    b.Property<string>("TriggerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreEventKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("DispatchMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DispatchWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterExpression")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleJson")
                        .HasColumnType("TEXT");

                    b.HasKey("TriggerId");

                    b.HasIndex("AutomationId", "CoreEventKey")
                        .IsUnique()
                        .HasFilter("CoreEventKey IS NOT NULL");

                    b.HasIndex("AutomationId", "EventId")
                        .IsUnique()
                        .HasFilter("EventId IS NOT NULL");

                    b.HasIndex("AutomationId", "Kind")
                        .IsUnique()
                        .HasFilter("Kind = 0");

                    b.HasIndex("EventId", "Enabled");

                    b.ToTable("AutomationTriggers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AutomationTriggers_Dispatch", "(DispatchMode = 0 AND DispatchWindowSeconds IS NULL) OR (DispatchMode = 1 AND DispatchWindowSeconds BETWEEN 60 AND 3600)");

                            t.HasCheckConstraint("CK_AutomationTriggers_Identity", "length(TriggerId) = 36 AND TriggerId <> '00000000-0000-0000-0000-000000000000' AND Revision >= 1");

                            t.HasCheckConstraint("CK_AutomationTriggers_Source", "(Kind = 0 AND ScheduleJson IS NOT NULL AND EventId IS NULL AND CoreEventKey IS NULL AND FilterExpression IS NULL AND DispatchMode = 0 AND DispatchWindowSeconds IS NULL) OR (Kind = 1 AND ScheduleJson IS NULL AND EventId IS NOT NULL AND CoreEventKey IS NULL) OR (Kind = 2 AND ScheduleJson IS NULL AND EventId IS NULL AND CoreEventKey IN ('run.completed','run.failed','session.completed','session.ended','instance.config_changed','harness.definition_adopted'))");
                        });
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.BackgroundCompletionReceiptRecord", b =>
                {
                    b.Property<string>("ChildAgentRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InboxJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentActivationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.Property<string>("SkipReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChildAgentRunId");

                    b.HasIndex("ClaimRunId");

                    b.HasIndex("ParentActivationId")
                        .HasFilter("ParentActivationId IS NOT NULL");

                    b.HasIndex("Status", "CreatedAtUtc", "ChildAgentRunId");

                    b.HasIndex("AgentInstanceId", "ProfileId", "ParentSessionId", "CreatedAtUtc", "ChildAgentRunId");

                    b.ToTable("BackgroundCompletionReceipts", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.BrowserPrivacyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BrowserPrivacy", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.CoreEventBucketRecord", b =>
                {
                    b.Property<string>("BucketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverageJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DueAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Flushed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TriggerRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("BucketId");

                    b.HasIndex("Flushed", "DueAtUtc");

                    b.ToTable("CoreEventBuckets", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.CoreEventDeliveryRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "TriggerId");

                    b.HasIndex("AgentInstanceId", "ProfileId", "Status");

                    b.ToTable("CoreEventDeliveries", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.CoreEventRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Snapshotted")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Snapshotted", "ReceivedAtUtc", "EventId");

                    b.ToTable("CoreEvents", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.CredentialRecord", b =>
                {
                    b.Property<string>("CredentialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedOriginsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtectionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("CredentialId");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.EntryRecord", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationMessageEffectKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentRefsJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvelopeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReferenceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeardTextEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterruptReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelCatalogKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProviderAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceivedTextEndExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAdmissionFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPartsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("SessionId", "EntrySequence")
                        .IsUnique();

                    b.HasIndex("SessionId", "SourceEventId")
                        .IsUnique()
                        .HasFilter("SourceEventId IS NOT NULL");

                    b.ToTable("ConversationEntries", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ExperienceRecord", b =>
                {
                    b.Property<string>("ExperienceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ThroughCursor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExperienceId");

                    b.HasIndex("AgentInstanceId", "CreatedAtUtc");

                    b.HasIndex("AgentInstanceId", "SourceKind", "SourceId", "ThroughCursor")
                        .IsUnique();

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ExperienceSettingsRecord", b =>
                {
                    b.Property<string>("AgentInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentInstanceId");

                    b.ToTable("ExperienceSettings");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ExternalEventDeliveryRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "TriggerId");

                    b.HasIndex("Status", "EventId", "TriggerId");

                    b.ToTable("ExternalEventDeliveries", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ExternalEventRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("AdmittedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("ResourceId", "SourceEventId")
                        .IsUnique();

                    b.ToTable("ExternalEvents", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.IdentityMaintenanceSettingsRecord", b =>
                {
                    b.Property<string>("AgentInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowAgentConsolidation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentInstanceId");

                    b.ToTable("IdentityMaintenanceSettings");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.MessageAttachmentRow", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "AttachmentId");

                    b.HasIndex("SessionId");

                    b.ToTable("MessageAttachments", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.OwnerCapabilityRecord", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenHash");

                    b.ToTable("OwnerCapabilities", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ProfileRecord", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurablyDeletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{\"kind\":0}");

                    b.Property<string>("PauseReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingAgentInputIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedPersonaJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PinnedPersonaRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RuntimeEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Surfaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WorkspaceOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("SessionId");

                    b.HasIndex("AgentInstanceId");

                    b.HasIndex("DurablyDeletedAtUtc", "ArchivedAtUtc", "UpdatedAtUtc", "SessionId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SnapshotRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentCompletion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeadlineAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUserActivityAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LifecycleChangedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelCatalogKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ModelHasExplicitReasoningEffort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProviderAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelSelectionSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingTopic")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeechLocaleOverride")
                        .HasColumnType("TEXT");

                    b.Property<long>("SummarizedThroughEntrySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SummaryFormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SummaryGeneratedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryModelCatalogKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModelProviderAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModelReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UserCancellationAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UserCompletionAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("SessionSnapshots", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.StructuredMemoryRecord", b =>
                {
                    b.Property<string>("MemoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DerivedFromMemoryIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaintenanceAgentInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceAgentRunId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginMemoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProvenanceRecordedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEntryIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersedesMemoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemoryId");

                    b.HasIndex("SessionId", "Status");

                    b.HasIndex("OwnerProfileId", "Kind", "SubjectKey")
                        .IsUnique()
                        .HasDatabaseName("IX_StructuredMemories_UserOwner_Kind_SubjectKey")
                        .HasFilter("Status = 0 AND Scope = 2");

                    b.HasIndex("SessionId", "Kind", "SubjectKey")
                        .IsUnique()
                        .HasFilter("Status = 0 AND Scope = 0");

                    b.HasIndex("OwnerInstanceId", "OwnerProfileId", "Kind", "SubjectKey")
                        .IsUnique()
                        .HasFilter("Status = 0 AND Scope = 1");

                    b.ToTable("StructuredMemories", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.TriggerOccurrenceRecord", b =>
                {
                    b.Property<string>("OccurrenceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedAgentRunId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("AdmittedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimLeaseExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DispositionReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionTargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LiveEvaluationCompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiveSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelCatalogKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProviderAlias")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelReasoningEffort")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelSource")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ObservedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportToSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoutingRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RoutingUpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TriggerRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("OccurrenceId");

                    b.HasIndex("AcceptedAgentRunId")
                        .IsUnique()
                        .HasFilter("AcceptedAgentRunId IS NOT NULL");

                    b.HasIndex("ExecutionSessionId");

                    b.HasIndex("LiveSessionId");

                    b.HasIndex("Disposition", "ClaimLeaseExpiresAtUtc");

                    b.HasIndex("AgentInstanceId", "ProfileId", "DedupeKey")
                        .IsUnique();

                    b.HasIndex("AgentInstanceId", "ProfileId", "Disposition");

                    b.ToTable("TriggerOccurrences", null, t =>
                        {
                            t.HasCheckConstraint("CK_TriggerOccurrences_Destination", "(ExecutionTargetKind = 0 AND TargetSessionId IS NULL) OR (ExecutionTargetKind = 1 AND TargetSessionId IS NOT NULL AND ReportToSessionId IS NULL)");

                            t.HasCheckConstraint("CK_TriggerOccurrences_ExecutionLink", "(ExecutionSessionId IS NULL AND AcceptedAgentRunId IS NULL) OR (ExecutionSessionId IS NOT NULL AND LiveSessionId IS NULL AND AcceptedAgentRunId IS NOT NULL) OR (ExecutionSessionId IS NULL AND LiveSessionId IS NOT NULL AND AcceptedAgentRunId IS NOT NULL AND LiveEvaluationCompletedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.WebhookEventRecord", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.ToTable("WebhookEvents", (string)null);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ActivationRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.ActivationSourceEntryRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.ActivationRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentCore.Infrastructure.Persistence.EntryRecord", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentCredentialBindingRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("AgentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentCore.Infrastructure.Persistence.CredentialRecord", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionResourceStateRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentDefinitionSkillStateRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("AgentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentInstanceResourceRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentInstanceSkillRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("AgentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AgentRunRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.ActivationRecord", null)
                        .WithOne()
                        .HasForeignKey("AgentCore.Infrastructure.Persistence.AgentRunRecord", "ActivationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AutomationTriggerRecordEntity", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AutomationRecord", null)
                        .WithMany("Triggers")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.BackgroundCompletionReceiptRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentRunRecord", null)
                        .WithOne()
                        .HasForeignKey("AgentCore.Infrastructure.Persistence.BackgroundCompletionReceiptRecord", "ChildAgentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentCore.Infrastructure.Persistence.ActivationRecord", null)
                        .WithMany()
                        .HasForeignKey("ParentActivationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.EntryRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SnapshotRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", "Session")
                        .WithOne("Snapshot")
                        .HasForeignKey("AgentCore.Infrastructure.Persistence.SnapshotRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.TriggerOccurrenceRecord", b =>
                {
                    b.HasOne("AgentCore.Infrastructure.Persistence.AgentRunRecord", null)
                        .WithMany()
                        .HasForeignKey("AcceptedAgentRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExecutionSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgentCore.Infrastructure.Persistence.SessionRecord", null)
                        .WithMany()
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.AutomationRecord", b =>
                {
                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("AgentCore.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
