import { Checkbox, Flex, theme, Typography } from "antd";
import { useId, useRef } from "react";

export const automationTriggerPermissions = [
  { value: "schedule", label: "Schedule", description: "Allow Automations to run at configured times." },
  { value: "coreEvent", label: "Built-in Events", description: "Trusted events generated by Agent Core." },
  { value: "applicationEvent", label: "Webhook Events", description: "Authenticated external events." }
] as const;

export function automationTriggerPermissionSummary(values: readonly string[] = []): string {
  return automationTriggerPermissions.map(p => `${p.label}: ${values.includes(p.value) ? "Allowed" : "Not allowed"}`).join(" · ");
}

export function AutomationTriggerPermissions({ values, enabled, disabled, onChange }: {
  values: string[]; enabled: boolean; disabled: boolean; onChange: (values: string[]) => void;
}) {
  const { token } = theme.useToken();
  const id = useId();
  // Only a local undo choice; checked states and saved authority always derive from values.
  const pausedChoices = useRef<string[] | null>(null);
  const eventValues = ["coreEvent", "applicationEvent"];
  const selected = eventValues.filter(value => values.includes(value));
  const partial = selected.length === 1;
  const write = (next: string[]) => onChange([...new Set(next)]);
  const permission = (p: typeof automationTriggerPermissions[number]) => (
    <Flex key={p.value} vertical gap={token.paddingXXS}>
      <Checkbox checked={values.includes(p.value)} disabled={disabled} aria-describedby={`${id}-${p.value}`}
        onChange={e => {
          if (p.value !== "schedule") pausedChoices.current = null;
          write(e.target.checked ? [...values, p.value] : values.filter(value => value !== p.value));
        }}>{p.label}</Checkbox>
      <Typography.Text id={`${id}-${p.value}`} type="secondary" style={{ paddingInlineStart: token.paddingLG }}>{p.description}</Typography.Text>
    </Flex>
  );
  return <section aria-label="Automation trigger permissions" className="admin-draft-form-section">
    <Typography.Text strong>Automation trigger permissions</Typography.Text>
    {!enabled && <Typography.Text type="secondary">Automation is disabled. These permissions stay configured but do not authorize execution.</Typography.Text>}
    {permission(automationTriggerPermissions[0])}
    <Flex vertical gap={token.paddingXXS}>
      <Checkbox checked={selected.length > 0} indeterminate={partial} aria-checked={partial ? "mixed" : selected.length > 0}
        disabled={disabled} aria-describedby={`${id}-events`} onChange={() => {
          if (selected.length) {
            pausedChoices.current = selected;
            write(values.filter(value => !eventValues.includes(value)));
          } else write([...values, ...(pausedChoices.current ?? eventValues)]);
        }}>Events</Checkbox>
      <Typography.Text id={`${id}-events`} type="secondary" style={{ paddingInlineStart: token.paddingLG }}>
        Allow Automations to respond to events. Turning on restores paused choices, or allows both families initially.
      </Typography.Text>
    </Flex>
    <Flex vertical gap={token.paddingSM} style={{ paddingInlineStart: token.paddingLG }} role="group" aria-label="Event families">
      {automationTriggerPermissions.slice(1).map(permission)}
    </Flex>
  </section>;
}
