import { expect, test } from "@playwright/test";
import { selectInstanceIdentity, INSTANCE_DEFINITIONS } from "./support/instance-identity";
import { waitForResponseSettled } from "./support/response-settled";
import type { BackgroundSession, CursorPage, SessionAutomation } from "../src/services/api";

test("a natural 30-second greeting stays in its exact conversation after navigation and reload", async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await selectInstanceIdentity(page, INSTANCE_DEFINITIONS.generalAssistant);
  await expect(page.getByTestId("connection")).toHaveText("Ready");
  await page.getByLabel("Message", { exact: true }).fill("Say hello to me in 30 seconds.");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.locator(".conversation-scroll")).toContainText("I'll say hello in this chat in 30 seconds.");
  await waitForResponseSettled(page);
  const parentUrl = page.url();
  const id = parentUrl.split("/").at(-1)!;
  const token = (await page.evaluate(() => localStorage.getItem("agent-core.owner-capability")))!;
  const headers = { "X-AgentCore-Owner-Capability": token };
  const parent = await (await page.request.get(`/api/v2/sessions/${id}`, { headers })).json();
  const rows = (await (await page.request.get(`/api/v2/sessions/${id}/automations`, { headers })).json()).items as SessionAutomation[];
  expect(rows).toHaveLength(1);
  expect(rows[0].executionTarget).toEqual({ kind: "existingSession", sessionId: id });
  expect(rows[0].completionDelivery).toEqual({ kind: "none", sessionId: null });
  await page.getByRole("button", { name: "Automations", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "Automations", exact: true });
  await expect(drawer).toContainText("This conversation");
  await page.keyboard.press("Escape");
  await page.goto("/admin/instances"); // detach the original transport while its durable input waits
  await expect.poll(async () => {
    const history = await (await page.request.get(`/api/v1/sessions/${id}/messages?limit=100`, { headers })).json();
    return history.items.some((entry: { text: string }) => entry.text === "Hello!");
  }, { timeout: 45_000 }).toBe(true);
  await page.goto(parentUrl);
  await expect(page.getByTestId("connection")).toHaveText("Ready");
  await expect(page.locator(".chat-message-assistant").last()).toContainText("Hello!");
  await expect(page.locator(".chat-message-user")).toHaveCount(1);
  await page.reload();
  await expect(page.locator(".chat-message-assistant .assistant-body").filter({ hasText: /^Hello!$/ })).toHaveCount(1);
  const children = await (await page.request.get(`/api/v2/agent-instances/${parent.agentInstanceId}/background-sessions`, { headers })).json() as CursorPage<BackgroundSession>;
  expect(children.items).toEqual([]);
  expect(errors).toEqual([]);
});

test("Admin target and completion controls round-trip and reject a missing exact destination", async ({ page }) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await selectInstanceIdentity(page, INSTANCE_DEFINITIONS.generalAssistant);
  await expect(page.getByTestId("connection")).toHaveText("Ready");
  await page.getByLabel("Message", { exact: true }).fill("Hello");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page).toHaveURL(/\/c\/[0-9a-f-]{36}$/i);
  await expect(page.locator(".chat-message-assistant").last()).toContainText("Hello from synthetic.");
  await waitForResponseSettled(page);
  const parent = page.url().split("/").at(-1)!;
  const token = (await page.evaluate(() => localStorage.getItem("agent-core.owner-capability")))!;
  const headers = { "X-AgentCore-Owner-Capability": token };
  const session = await (await page.request.get(`/api/v2/sessions/${parent}`, { headers })).json();
  await page.goto(`/admin/instances/${session.agentInstanceId}/automation`);
  await page.getByRole("button", { name: "New automation", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "New automation", exact: true });
  await drawer.getByLabel("Automation name", { exact: true }).fill("Exact conversation greeting");
  await drawer.getByLabel("Automation instructions", { exact: true }).fill("Say hello once in this conversation");
  await drawer.getByRole("combobox", { name: "Automation destination", exact: true }).click();
  await page.getByText("Selected conversation", { exact: true }).last().click();
  await expect(drawer.getByRole("combobox", { name: "Automation completion report", exact: true })).toHaveCount(0);
  await expect(drawer.getByRole("button", { name: "Create automation", exact: true })).toBeDisabled();
  await drawer.getByRole("combobox", { name: "Destination conversation", exact: true }).click();
  await page.locator(".ant-select-item-option").filter({ hasText: parent.slice(0, 8) }).click();
  await expect(drawer.getByRole("switch", { name: "Enable automation", exact: true })).not.toBeChecked();
  await drawer.getByRole("switch", { name: "Enable automation", exact: true }).click();
  await drawer.getByRole("button", { name: "Create automation", exact: true }).click();
  await expect(drawer).toBeHidden();
  const source = page.getByRole("button", { name: "View automation: Exact conversation greeting", exact: true });
  await expect(source).toBeFocused();
  if (await source.getAttribute("aria-expanded") !== "true") await source.click();
  await page.getByRole("button", { name: "Run automation now", exact: true }).click();
  await expect(page.getByText(/Completed · Response/).first()).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "Edit automation", exact: true }).click();
  const editor = page.getByRole("dialog", { name: "Edit automation", exact: true });
  await expect(editor.getByText("Selected conversation", { exact: true })).toBeVisible();
  await expect(editor).toContainText(parent);
  await page.keyboard.press("Escape");
  await page.goto(`/c/${parent}`);
  await expect(page.locator(".chat-message-assistant").last()).toContainText("Hello!");
  await page.goto(`/admin/instances/${session.agentInstanceId}/automation`);
  await page.getByRole("button", { name: "New automation", exact: true }).click();
  const background = page.getByRole("dialog", { name: "New automation", exact: true });
  await background.getByLabel("Automation name", { exact: true }).fill("Background check with requested report");
  await background.getByLabel("Automation instructions", { exact: true }).fill("synthetic-automation-attention: report the actual progress");
  await expect(background.getByText("None", { exact: true })).toBeVisible();
  await background.getByRole("combobox", { name: "Automation completion report", exact: true }).click();
  await page.getByText("Selected conversation", { exact: true }).last().click();
  await expect(background.getByRole("button", { name: "Create automation", exact: true })).toBeDisabled();
  await background.getByRole("combobox", { name: "Report destination", exact: true }).click();
  await page.locator(".ant-select-item-option").filter({ hasText: parent.slice(0, 8) }).click();
  await expect(background.getByRole("switch", { name: "Enable automation", exact: true })).not.toBeChecked();
  await background.getByRole("switch", { name: "Enable automation", exact: true }).click();
  await background.getByRole("button", { name: "Create automation", exact: true }).click();
  await expect(background).toBeHidden();
  const details = page.getByRole("region", { name: "Automation details", exact: true }).filter({ hasText: "synthetic-automation-attention" });
  await expect(details).toContainText("Reports to:");
  await details.getByRole("button", { name: "Edit automation", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Edit automation", exact: true })).toContainText(parent);
  await page.keyboard.press("Escape");
  await details.getByRole("button", { name: "Run automation now", exact: true }).click();
  await page.goto(`/c/${parent}`);
  await expect(page.locator(".chat-message-assistant").last()).toContainText("Background work completed", { timeout: 30_000 });
  await page.getByRole("button", { name: /^Background work/ }).click();
  await expect(page.getByRole("dialog", { name: "Background work", exact: true })).toContainText("Completion: Reported");
  expect(errors).toEqual([]);
});
