import { expect, test } from '@playwright/test';

test('Admin authors scheduled work, runs through background execution, edits and disables at desktop and mobile widths', async ({ page }) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('requestfailed', request => { if (!request.failure()?.errorText.includes('ERR_ABORTED')) errors.push(request.url()); });
  await page.goto('/admin');
  await page.getByRole('button', { name: 'New instance', exact: true }).click();
  await page.getByRole('combobox', { name: 'Definition', exact: true }).click();
  await page.getByRole('combobox', { name: 'Definition', exact: true }).fill('general-assistant');
  await page.locator('.ant-select-item-option').filter({ hasText: 'General Assistant' }).click();
  await page.getByRole('button', { name: 'Create instance', exact: true }).click();
  await page.getByRole('tab', { name: 'Behavior & continuity', exact: true }).click();
  const schedules = page.getByRole('region', { name: 'Scheduled work', exact: true });
  await expect(schedules.getByText(/No scheduled work yet/)).toBeVisible();
  await schedules.getByRole('button', { name: 'New schedule', exact: true }).click();
  await expect(schedules.getByRole('button', { name: 'Create schedule', exact: true })).toBeDisabled();
  await schedules.getByLabel('Schedule task', { exact: true }).fill('Review pending store orders');
  await schedules.getByLabel('Schedule time zone', { exact: true }).fill('Asia/Ho_Chi_Minh');
  await schedules.getByLabel('Schedule maximum occurrences', { exact: true }).fill('0');
  await expect(schedules.getByRole('button', { name: 'Create schedule', exact: true })).toBeDisabled();
  await schedules.getByLabel('Schedule maximum occurrences', { exact: true }).fill('5');
  await schedules.getByRole('button', { name: 'Create schedule', exact: true }).click();
  await expect(schedules.getByLabel('Schedule task', { exact: true })).toBeHidden({ timeout: 30_000 });
  await schedules.getByText('Review pending store orders', { exact: true }).click();
  await expect(schedules.getByText('Admin owner', { exact: true })).toBeVisible();
  const instanceId = page.url().split('/').pop()!;
  const token = (await page.evaluate(() => localStorage.getItem('agent-core.owner-capability')))!;
  const headers = { 'X-AgentCore-Owner-Capability': token };
  const before = await page.request.get(`/api/v2/admin/agent-instances/${instanceId}/schedules`, { headers });
  const row = (await before.json()).items[0];
  expect(row.authorizationOrigin).toBe('AdminOwner');
  expect(row.sourceSessionId).toBeNull();
  expect(row.schedule.maxOccurrences).toBe(5);
  await expect(schedules.getByText('Originally created from', { exact: true })).toBeVisible();
  let calls = 0;
  await page.route(`**/agent-instances/${instanceId}/schedules/*/run`, async route => { calls++; await route.continue(); });
  const run = schedules.getByRole('button', { name: 'Run schedule now', exact: true });
  await run.evaluate(button => { (button as HTMLButtonElement).click(); (button as HTMLButtonElement).click(); });
  await expect(schedules.getByText('Completed', { exact: true })).toBeVisible({ timeout: 30_000 });
  expect(calls).toBe(1);
  await schedules.getByRole('button', { name: 'Inspect scheduled execution', exact: true }).click();
  const work = page.getByRole('dialog', { name: 'Background work', exact: true });
  await expect(work.getByText('Scheduled reminder', { exact: true })).toBeVisible();
  expect(await work.getByRole('button', { name: /Create/ }).count()).toBe(0);
  await work.getByRole('button', { name: 'Close', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await schedules.getByRole('button', { name: 'Edit schedule', exact: true }).click();
  await schedules.getByLabel('Schedule task', { exact: true }).fill('Review store orders with a deliberately longer task description that wraps at a narrow viewport');
  await schedules.getByRole('button', { name: 'Save schedule', exact: true }).click();
  await schedules.getByRole('button', { name: 'Disable schedule', exact: true }).click();
  await expect(run).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.reload();
  await page.getByRole('tab', { name: 'Behavior & continuity', exact: true }).click();
  await schedules.getByText(/Review store orders with a deliberately longer/).click();
  await expect(schedules.getByRole('button', { name: 'Enable schedule', exact: true })).toBeVisible();
  const persisted = (await (await page.request.get(`/api/v2/admin/agent-instances/${instanceId}/schedules`, { headers })).json()).items[0];
  expect(persisted.authorizationOrigin).toBe('AdminOwner'); expect(persisted.status).toBe('Disabled'); expect(persisted.lastWorkItemId).toBeTruthy();
  await schedules.getByRole('button', { name: 'Cancel schedule', exact: true }).click();
  await page.getByRole('dialog', { name: 'Cancel this schedule?', exact: true }).getByRole('button', { name: 'Cancel schedule', exact: true }).click();
  await expect(schedules.getByText('Cancelled', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
