import { expect, test } from '@playwright/test';

test('Admin authors scheduled work, runs through background execution, edits and disables at desktop and mobile widths', async ({ page }) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on('console', message => { if (message.type() === 'error' && !message.text().startsWith('Warning: [antd:')) errors.push(message.text()); });
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  page.on('pageerror', error => errors.push(error.message));
  page.on('requestfailed', request => { if (!request.failure()?.errorText.includes('ERR_ABORTED')) errors.push(request.url()); });
  await page.goto('/admin');
  await page.getByRole('button', { name: 'New instance', exact: true }).click();
  await page.getByRole('combobox', { name: 'Definition', exact: true }).click();
  await page.getByRole('combobox', { name: 'Definition', exact: true }).fill('general-assistant');
  await page.locator('.ant-select-item-option').filter({ hasText: 'General Assistant' }).click();
  await page.getByRole('combobox', { name: 'Published version', exact: true }).click();
  await page.getByRole('combobox', { name: 'Published version', exact: true }).fill('v9');
  await page.locator('.ant-select-item-option').filter({ hasText: 'v9 · Built-in · Published' }).click();
  await page.getByRole('button', { name: 'Create instance', exact: true }).click();
  await page.getByRole('tab', { name: 'Continuity', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Memory', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Experience', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Experience', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Automation', exact: true }).click();
  const schedules = page.getByRole('region', { name: 'Schedules', exact: true });
  await expect(schedules.getByText(/No schedules yet/)).toBeVisible();
  await schedules.getByRole('button', { name: 'New schedule', exact: true }).click();
  await expect(schedules.getByRole('button', { name: 'Create schedule', exact: true })).toBeDisabled();
  await schedules.getByLabel('Schedule task', { exact: true }).fill('Review pending store orders');
  await schedules.getByLabel('Schedule time zone', { exact: true }).fill('Asia/Ho_Chi_Minh');
  await schedules.getByLabel('Schedule maximum occurrences', { exact: true }).fill('0');
  await expect(schedules.getByRole('button', { name: 'Create schedule', exact: true })).toBeDisabled();
  await schedules.getByLabel('Schedule maximum occurrences', { exact: true }).fill('5');
  await schedules.getByRole('button', { name: 'Create schedule', exact: true }).click();
  await expect(schedules.getByLabel('Schedule task', { exact: true })).toBeHidden({ timeout: 30_000 });
  await schedules.getByRole('button', { name: 'View schedule: Review pending store orders', exact: true }).click();
  await expect(schedules.getByRole('region', { name: 'Schedule details', exact: true }).getByText('Admin owner', { exact: true })).toBeVisible();
  const instanceId = page.url().split('/').pop()!;
  const token = (await page.evaluate(() => localStorage.getItem('agent-core.owner-capability')))!;
  const headers = { 'X-AgentCore-Owner-Capability': token };
  const before = await page.request.get(`/api/v2/admin/agent-instances/${instanceId}/schedules`, { headers });
  const row = (await before.json()).items[0];
  expect(row.authorizationOrigin).toBe('AdminOwner');
  expect(row.sourceSessionId).toBeNull();
  expect(row.schedule.maxOccurrences).toBe(5);
  await expect(schedules.getByText('Originally created from', { exact: true })).toBeVisible();
  let calls = 0;
  await page.route(`**/agent-instances/${instanceId}/schedules/*/run`, async route => { calls++; await route.continue(); });
  const run = schedules.getByRole('button', { name: 'Run schedule now', exact: true });
  await run.evaluate(button => { (button as HTMLButtonElement).click(); (button as HTMLButtonElement).click(); });
  await expect(schedules.getByRole('region', { name: 'Schedule details', exact: true }).getByText('Completed', { exact: true })).toBeVisible({ timeout: 30_000 });
  expect(calls).toBe(1);
  await schedules.getByRole('button', { name: 'View last run', exact: true }).click();
  const work = page.getByRole('region', { name: 'Runs', exact: true });
  await expect(work.getByText('Schedule', { exact: true })).toBeVisible();
  expect(await work.getByRole('button', { name: /Create/ }).count()).toBe(0);
  const scheduledRun = page.locator('.background-work-selected');
  await expect(scheduledRun).toHaveAttribute('data-work-item-id', /.+/);
  await scheduledRun.getByRole('button', { name: 'View schedule', exact: true }).click();
  await expect(schedules.getByRole('button', { name: 'View schedule: Review pending store orders', exact: true })).toBeFocused();
  await page.getByRole('tab', { name: 'Thoughts', exact: true }).click();
  const thoughts = page.getByRole('region', { name: 'Thoughts', exact: true });
  await expect(thoughts.getByText(/No thoughts configured/)).toBeVisible();
  await thoughts.getByLabel('Thinking prompt', { exact: true }).fill('Review current obligations. Do nothing unless useful action exists.');
  await thoughts.getByRole('switch', { name: 'Enable thought activation', exact: true }).click();
  await thoughts.getByRole('button', { name: 'Create thought', exact: true }).click();
  await thoughts.getByRole('button', { name: /^View thought: Review current/ }).click();
  await thoughts.getByRole('button', { name: 'Run now', exact: true }).click();
  await expect(thoughts.getByText('No action', { exact: true }).first()).toBeVisible({ timeout: 30_000 });
  await thoughts.getByRole('button', { name: 'View run', exact: true }).click();
  await expect(page.locator('.background-work-selected')).toHaveText(/Thought/);
  await expect(work.getByText('Schedule', { exact: true })).toBeVisible();
  await expect(work.getByText('Thought', { exact: true })).toBeVisible();
  await page.locator('.background-work-selected').getByRole('button', { name: 'View thought', exact: true }).click();
  await expect(thoughts.getByRole('button', { name: /^View thought: Review current/ })).toBeFocused();
  await page.getByRole('tab', { name: 'Schedules', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await schedules.getByRole('button', { name: 'View last run', exact: true }).click();
  await page.locator('.background-work-selected').getByRole('button', { name: 'View schedule', exact: true }).click();
  await schedules.getByRole('button', { name: 'Edit schedule', exact: true }).click();
  await schedules.getByLabel('Schedule task', { exact: true }).fill('Review store orders with a deliberately longer task description that wraps at a narrow viewport');
  await schedules.getByRole('button', { name: 'Save schedule', exact: true }).click();
  await schedules.getByRole('button', { name: 'Disable schedule', exact: true }).click();
  await expect(run).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.reload();
  await page.getByRole('tab', { name: 'Automation', exact: true }).click();
  await schedules.getByRole('button', { name: /^View schedule: Review store orders with a deliberately longer/ }).click();
  await expect(schedules.getByRole('button', { name: 'Enable schedule', exact: true })).toBeVisible();
  const persisted = (await (await page.request.get(`/api/v2/admin/agent-instances/${instanceId}/schedules`, { headers })).json()).items[0];
  expect(persisted.authorizationOrigin).toBe('AdminOwner'); expect(persisted.status).toBe('Disabled'); expect(persisted.lastWorkItemId).toBeTruthy();
  await schedules.getByRole('button', { name: 'Cancel schedule', exact: true }).click();
  await page.getByRole('dialog', { name: 'Cancel this schedule?', exact: true }).getByRole('button', { name: 'Cancel schedule', exact: true }).click();
  await expect(schedules.getByText('Cancelled', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Thoughts', exact: true }).click();
  await thoughts.getByRole('button', { name: /^View run: Review current/ }).click();
  await page.locator('.background-work-selected').getByRole('button', { name: 'View thought', exact: true }).click();
  await thoughts.getByRole('button', { name: 'Disable thought', exact: true }).click();
  await expect(thoughts.getByRole('button', { name: 'Run now', exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});
