import { expect, test, type Page } from '@playwright/test';

test.use({ actionTimeout: 15_000 });

async function select(page: Page, label: string, text: string) {
  await page.getByRole('combobox', { name: label, exact: true }).click();
  if (label === 'Identity' || label === 'Published version' || label === 'Definition') await page.getByRole('combobox', { name: label, exact: true }).fill(text);
  await page.locator('.ant-select-item-option').filter({ hasText: text }).last().click();
}
async function send(page: Page, text: string) {
  await page.getByLabel('Message', { exact: true }).fill(text);
  await page.getByRole('button', { name: 'Send', exact: true }).click();
}

test('Experience informs an approved thought; next activation stays quiet; owner controls work at narrow width', async ({ page }) => {
  test.setTimeout(150_000);
  const errors: string[] = [];
  const reviewerName = `Continuity reviewer ${Date.now()}`;
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !message.text().startsWith('Warning: [antd: List]')) errors.push(message.text()); });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await send(page, 'Hello');
  await expect(page.getByText('Hello from synthetic.', { exact: true }).last()).toBeVisible();
  await page.getByRole('button', { name: 'Open Admin' }).click();
  await page.getByRole('button', { name: 'New instance', exact: true }).click();
  await select(page, 'Definition', 'General Assistant · general-assistant');
  await select(page, 'Published version', 'v9 · Built-in · Published');
  const dialog = page.getByRole('dialog', { name: 'New instance', exact: true });
  await dialog.getByText('Custom persona', { exact: true }).click();
  await dialog.getByLabel('Persona name').fill(reviewerName);
  await dialog.getByLabel('Persona role').fill('Store review');
  await dialog.getByLabel('Persona description').fill('Review observable outcomes.');
  await dialog.getByLabel('Persona tone').fill('Clear');
  await dialog.getByText('Harness management (optional)', { exact: true }).click();
  await select(page, 'Authoring mode', 'Assisted');
  await dialog.getByLabel('Knowledge & resources', { exact: true }).uncheck();
  await dialog.getByLabel('Skills', { exact: true }).check();
  await dialog.getByRole('button', { name: 'Create instance', exact: true }).click();
  await expect(page.getByRole('heading', { name: reviewerName, exact: true })).toBeVisible();
  const id = page.url().split('/').at(-1)!;
  await page.getByRole("tab", { name: "Continuity", exact: true }).click();
  await page.getByRole("tab", { name: "Experience", exact: true }).click();
  const experience = page.getByRole('region', { name: 'Experience', exact: true });
  const initiative = page.getByRole('region', { name: 'Thoughts', exact: true });
  await expect(experience.getByText('No experience yet. Enable experience and retrospect a completed task.')).toBeVisible();
  await experience.getByRole('switch', { name: 'Enable experience', exact: true }).click();
  await expect(experience.getByText('Enabled · completed work may be retrospected')).toBeVisible();
  await page.locator('.admin-header').getByRole('button', { name: /Chat$/ }).first().click();
  await select(page, 'Identity', reviewerName);
  await send(page, 'synthetic-fail-turn');
  await expect(page.getByText(/Synthetic turn failure|could not complete|failed/i).last()).toBeVisible();
  await send(page, 'A correction: observe the current page before acting.');
  await expect(page.getByText('Hello from synthetic.', { exact: true }).last()).toBeVisible();
  const sessionId = page.url().split('/').at(-1)!;
  const ownerToken = await page.evaluate(() => localStorage.getItem('agent-core.owner-capability'));
  const source = await page.request.get(`/api/v2/sessions/${sessionId}`, { headers: { 'X-AgentCore-Owner-Capability': ownerToken! } });
  expect((await source.json()).agentInstanceId).toBe(id);
  const paused = await page.request.post(`/api/v2/sessions/${sessionId}/deactivate`, { headers: { 'X-AgentCore-Owner-Capability': ownerToken! } });
  expect(paused.ok()).toBe(true);
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open Admin' }).click();
  await page.goto(`/admin/instances/${id}`);
  await page.getByRole("tab", { name: "Continuity", exact: true }).click();
  await page.getByRole("tab", { name: "Experience", exact: true }).click();
  // Persisted pause admits automatic retrospection; explicit request resolves to that checkpoint.
  await expect(experience.getByRole('button', { name: 'View experience: Review observable completed work', exact: true }).first()).toBeVisible({ timeout: 30_000 });
  await experience.getByLabel('Retrospection source Session', { exact: true }).fill(sessionId);
  await experience.getByRole('button', { name: 'Retrospect now', exact: true }).click();
  await expect(experience.getByRole('button', { name: 'View experience: Review observable completed work', exact: true }).first()).toBeVisible({ timeout: 30_000 });
  await page.getByRole('tab', { name: 'Continuity', exact: true }).click();
  await page.getByRole('tab', { name: 'Experience', exact: true }).click();
  await experience.getByRole('button', { name: 'View experience: Review observable completed work', exact: true }).first().click();
  await expect(experience.getByText('The user supplied a correction', { exact: true })).toBeVisible();
  await experience.getByRole('button', { name: 'Retrospect now', exact: true }).click();
  await expect(experience.getByRole('button', { name: 'View experience: Review observable completed work', exact: true })).toHaveCount(1);
  await page.locator('.admin-header').getByRole('button', { name: /Chat$/ }).first().click();
  await page.getByRole('button', { name: 'Start a new chat', exact: true }).click();
  await select(page, 'Identity', 'Continuity reviewer');
  await send(page, 'Use my recent experience before acting.');
  await expect(page.getByText('I will observe current page state before acting, based on earlier experience. Current policy still controls every action.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open Admin' }).click();
  await page.goto(`/admin/instances/${id}`);
  await page.getByRole("tab", { name: "Continuity", exact: true }).click();
  await page.getByRole("tab", { name: "Experience", exact: true }).click();
  await page.getByRole('tab', { name: 'Automation', exact: true }).click();
  await page.getByRole('tab', { name: 'Thoughts', exact: true }).click();
  await initiative.getByLabel('Thinking prompt', { exact: true }).fill('synthetic-thought-improve: review recent experience and improve only when useful. Otherwise do nothing.');
  await initiative.getByRole('switch', { name: 'Enable thought activation', exact: true }).click();
  await initiative.getByRole('button', { name: 'Create thought', exact: true }).click();
  await expect(initiative.getByText('Every 1 hour', { exact: true })).toBeVisible();
  await initiative.getByRole('button', { name: /^View thought: synthetic-thought-improve:/ }).click();
  const runPattern = `**/api/v2/admin/agent-instances/${id}/thoughts/*/run`;
  const statusPattern = `**/api/v2/admin/agent-instances/${id}/thoughts`;
  const previousStatus = await page.request.get(`/api/v2/admin/agent-instances/${id}/thoughts`, {
    headers: { 'X-AgentCore-Owner-Capability': ownerToken! }
  });
  expect(previousStatus.ok()).toBe(true);
  const previousStatusBody = await previousStatus.text();
  await page.route(statusPattern, route => route.request().method() === 'GET'
    ? route.fulfill({ status: 200, contentType: 'application/json', body: previousStatusBody })
    : route.continue());
  let runRequests = 0;
  let releaseRun!: () => void;
  const runGate = new Promise<void>(resolve => { releaseRun = resolve; });
  await page.route(runPattern, async route => { runRequests++; await runGate; await route.continue(); });
  const runButton = initiative.getByRole('button', { name: 'Run now', exact: true });
  await runButton.evaluate(button => { (button as HTMLButtonElement).click(); (button as HTMLButtonElement).click(); });
  await expect(runButton).toBeDisabled();
  await expect(runButton).toHaveAttribute('aria-busy', 'true');
  await expect.poll(() => runRequests).toBe(1);
  releaseRun();
  await expect(initiative.getByRole('button', { name: 'Refresh thoughts', exact: true })).toBeEnabled();
  await expect(runButton).toBeDisabled();
  await expect(runButton).toHaveText('Starting…');
  await runButton.evaluate(button => (button as HTMLButtonElement).click());
  expect(runRequests).toBe(1);
  await page.unroute(statusPattern);
  await initiative.getByRole('button', { name: 'Refresh thoughts', exact: true }).click();

  await expect(initiative.getByText('Needs approval', { exact: true }).first()).toBeVisible({ timeout: 30_000 });
  expect(runRequests).toBe(1);
  await page.unroute(runPattern);
  await initiative.getByRole('button', { name: 'View run', exact: true }).click();
  const work = page.getByRole('region', { name: 'Runs', exact: true });
  await expect(work.getByText('Thought', { exact: true })).toBeVisible();
  await work.getByRole('button', { name: 'Approve Thought', exact: true }).click();
  await page.getByRole('dialog', { name: 'Approve this action?', exact: true }).getByRole('button', { name: 'Approve action', exact: true }).click();
  await expect(work.getByText(/Model:.*Action completed/)).toBeVisible({ timeout: 30_000 });
  await page.locator('.background-work-selected').getByRole('button', { name: 'View thought', exact: true }).click();
  await initiative.getByRole('button', { name: 'Refresh thoughts', exact: true }).click();
  await expect(initiative.getByText('Action completed', { exact: true }).first()).toBeVisible();
  await initiative.getByRole('button', { name: 'Run now', exact: true }).click();
  await expect(initiative.getByText('No action', { exact: true }).first()).toBeVisible({ timeout: 30_000 });
  const owner = await page.evaluate(() => localStorage.getItem('agent-core.owner-capability'));
  const response = await page.request.get(`/api/v2/admin/agent-instances/${id}/work-items`, { headers: { 'X-AgentCore-Owner-Capability': owner! } });
  expect(response.ok()).toBe(true);
  const data = await response.json();
  const thoughts = data.items.filter((item: { origin: string }) => item.origin === 'Thought activation');
  expect(thoughts).toHaveLength(2); expect(thoughts.every((item: { attentionRequired: boolean }) => !item.attentionRequired)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await initiative.getByRole('button', { name: 'Disable thought', exact: true }).click();
  await expect(initiative.getByRole('button', { name: 'Run now', exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.getByRole('tab', { name: 'Continuity', exact: true }).click();
  await page.getByRole('tab', { name: 'Experience', exact: true }).click();
  await experience.getByRole('button', { name: 'View experience: Review observable completed work', exact: true }).first().click();
  await experience.getByRole('button', { name: 'Suppress experience', exact: true }).first().click();
  await expect(experience.getByText('Suppressed', { exact: true }).first()).toBeVisible();
  await experience.getByRole('button', { name: 'Reset experience', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Reset experience', exact: true }).click();
  await expect(experience.getByText('No experience yet. Enable experience and retrospect a completed task.')).toBeVisible();
  await page.getByRole('tab', { name: 'Automation', exact: true }).click();
  await page.getByRole('tab', { name: 'Thoughts', exact: true }).click();
  await initiative.getByRole('button', { name: 'Delete thought', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete thought', exact: true }).click();
  await expect(initiative.getByText('No thoughts configured. Add one when you want this agent to periodically review whether action is useful.')).toBeVisible();
  expect(errors).toEqual([]);
});
