using AgentCore.Application.Ports;
using AgentCore.Domain.Definitions;
using AgentCore.Infrastructure.Definitions;
using System.Text.Json;

namespace AgentCore.Application.Tests;

/// <summary>Unit-scenario versions for policy regression; never part of the runtime catalog.</summary>
internal sealed class ScenarioDefinitionStore : IAgentDefinitionStore
{
    private readonly FileAgentDefinitionStore _current;
    private static readonly JsonSerializerOptions Json = new() { PropertyNameCaseInsensitive = true };
    public ScenarioDefinitionStore(string path, ProviderAliasSet aliases) => _current = new(path, aliases);
    public ValueTask<IReadOnlyList<AgentDefinition>> ListAsync(CancellationToken cancellationToken = default) => _current.ListAsync(cancellationToken);
    public async ValueTask<AgentDefinition?> GetAsync(string id, int? version = null, CancellationToken cancellationToken = default)
    {
        var current = await _current.GetAsync(id, null, cancellationToken);
        if (current is null || version is null || version == current.Version) return current;
        return (id, version) switch
        {
            ("general-assistant", 1) => current with { Version = 1, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = [] } },
            ("general-assistant", 2) => current with { Version = 2, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["web.search", "web.fetch"] } },
            ("general-assistant", 3) => current with { Version = 3, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["web.search", "web.fetch", "demo.sensitive_action"] } },
            ("general-assistant", 4) => current with { Version = 4, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["web.search", "web.fetch", "demo.sensitive_action", "email.search", "email.read", "email.create_draft", "email.send"] } },
            ("general-assistant", 5) => current with { Version = 5, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "demo.sensitive_action", "email.search", "email.read", "email.create_draft", "email.send"] } },
            ("general-assistant", 6) => current with { Version = 6, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "demo.sensitive_action", "email.search", "email.read", "email.create_draft", "email.send"] } },
            ("general-assistant", 7) => current with { Version = 7, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send"] } },
            ("general-assistant", 8) => current with { Version = 8, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowedSourceKinds":["schedule"]}""", Json), MemoryPolicy = MemoryPolicy.Disabled, Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel"] } },
            ("general-assistant", 9) => current with { Version = 9, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowedSourceKinds":["schedule"]}""", Json), MemoryPolicy = JsonSerializer.Deserialize<MemoryPolicy>("""{"sessionMemory":true,"identityUserPromotion":true,"identityUserRetrieval":true,"userPromotion":false,"userRetrieval":false}""", Json), Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel"] } },
            ("general-assistant", 10) => current with { Version = 10, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowFixedInterval":true,"minFixedIntervalSeconds":60,"allowedSourceKinds":["schedule"]}""", Json), MemoryPolicy = JsonSerializer.Deserialize<MemoryPolicy>("""{"sessionMemory":true,"identityUserPromotion":true,"identityUserRetrieval":true,"userPromotion":false,"userRetrieval":false}""", Json), Skills = [], Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel"] } },
            ("general-assistant", 11) => current with { Version = 11, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowFixedInterval":true,"minFixedIntervalSeconds":60,"allowedSourceKinds":["schedule"]}""", Json), MemoryPolicy = JsonSerializer.Deserialize<MemoryPolicy>("""{"sessionMemory":true,"identityUserPromotion":true,"identityUserRetrieval":true,"userPromotion":false,"userRetrieval":false}""", Json), Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel", "browser.navigate", "browser.observe", "browser.act"] } },
            ("general-assistant", 12) => current with { Version = 12, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowFixedInterval":true,"minFixedIntervalSeconds":60,"allowedSourceKinds":["schedule"]}""", Json), MemoryPolicy = JsonSerializer.Deserialize<MemoryPolicy>("""{"sessionMemory":true,"identityUserPromotion":true,"identityUserRetrieval":true,"userPromotion":false,"userRetrieval":false}""", Json), Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel", "browser.navigate", "browser.observe", "browser.act", "browser.close"] } },
            ("customer-support", 1) => current with { Version = 1, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.write", "artifacts.create", "artifacts.verify"] } },
            ("customer-support", 2) => current with { Version = 2, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":false,"allowOneShot":false,"allowDaily":false,"allowWeekly":false,"allowIndefiniteRecurrence":false,"maxActiveRegistrations":1,"oneShotHorizonDays":1,"minRecurrenceDays":1,"allowedSourceKinds":["applicationEvent"]}""", Json), MemoryPolicy = MemoryPolicy.Disabled, Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.write", "artifacts.create", "artifacts.verify"] } },
            ("compliance", 1) => current with { Version = 1, TriggerPolicy = null, MemoryPolicy = MemoryPolicy.Disabled, Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.write", "artifacts.create", "artifacts.verify"] } },
            ("secretary", 1) => current with { Version = 1, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowFixedInterval":true,"minFixedIntervalSeconds":60,"allowedSourceKinds":["schedule"]}""", Json), MemoryPolicy = JsonSerializer.Deserialize<MemoryPolicy>("""{"sessionMemory":true,"identityUserPromotion":true,"identityUserRetrieval":true,"userPromotion":false,"userRetrieval":false}""", Json), Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel", "browser.navigate", "browser.observe", "browser.act", "browser.close"] } },
            ("secretary", 2) => current with { Version = 2, TriggerPolicy = JsonSerializer.Deserialize<TriggerPolicy>("""{"enabled":true,"allowUserScheduling":true,"allowOneShot":true,"allowDaily":true,"allowWeekly":true,"allowIndefiniteRecurrence":true,"maxActiveRegistrations":32,"oneShotHorizonDays":365,"minRecurrenceDays":1,"allowFixedInterval":true,"minFixedIntervalSeconds":60,"allowedSourceKinds":["schedule","applicationEvent"]}""", Json), MemoryPolicy = JsonSerializer.Deserialize<MemoryPolicy>("""{"sessionMemory":true,"identityUserPromotion":true,"identityUserRetrieval":true,"userPromotion":false,"userRetrieval":false}""", Json), Skills = current.Skills, Environment = current.Environment! with { Capabilities = null, Projection = null, ToolAllowlist = ["knowledge.retrieve", "workspace.read", "workspace.list", "workspace.write", "workspace.patch", "workspace.search", "workspace.move", "artifacts.create", "artifacts.create_from_workspace", "artifacts.verify", "sandbox.run", "web.search", "web.fetch", "http.request", "email.search", "email.read", "email.create_draft", "email.send", "trigger.schedule_once", "trigger.schedule_recurring", "trigger.list", "trigger.update", "trigger.cancel", "browser.navigate", "browser.observe", "browser.act", "browser.close", "browser.capture", "browser.pages"] } },
            _ => null
        };
    }
}
